name: docker - Build and Push

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:
  push:

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./base
          file: ./base/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/archlinux:latest

  dev:
    runs-on: ubuntu-latest
    needs: base
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./dev
          file: ./dev/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/archlinux:dev
